### ISSUE TITLE
Stopped working?

### ISSUE THREAD

**Issue by jbishop129** [ianperrin/MMM-YouTubeChannelStats#6]
Hello,
I've been happily using this module for quite some time, even contributed a PR ;) In the last couple days it just stopped working for me. I've removed and reinstalled it, I've checked my Google API key and tried a different one, and I have two MagicMirrors in two different houses, both the YT module has stopped working, and just shows `Loading...` text. 

I tried using a different channel ID, and it works just fine! So, now I cannot figure out why it does not like my channel ID. 
`UCuDBkw9mGzkpExvGXZLfA-A`

I've added other channels to test, and they work fine. I even tracked down another channel that had a "dash" in the channel ID, to see if that was problematic, and it's just fine. I pulled up the channel by channel ID on SocialBlade, which (I think) tells me the API isn't having a problem with accessing the Channel ID. No errors or warnings, or any signs of throttling etc in the Google API dashboard/console, and as I said I tried a fresh API key too just to rule that out. Cant quite put my finger on this one. 

Also, I don't see anything in the logs, but it's possible I'm not looking in the right place. Any ideas?

**Comment by ianperrin** [comment]
Hi 

Sadly I’m not able to reproduce this issue, so let’s see what we can do.

As you can’t see anything in the logs, have you been able to check the browser console for errors?

Whilst viewing magic mirror, press F12 to open the DevTools, then go to the console. You may need to refresh the page to see further info, or select All to ensure all messages are displayed

Let me know what you find.

**Comment by jbishop129** [comment]
Sigh. The issue went away on its' own, presumably a transient error. Thanks for responding!
